### ISSUE TITLE
sentry cleanup fails

### ISSUE THREAD

**Issue by axinojolais** [snapcrafters/sentry#30]
Probably missing apparmor rules :
```
$ sudo sentry cleanup --project internal
Traceback (most recent call last):
  File "/snap/sentry/70/bin/sentry", line 10, in <module>
    sys.exit(main())
  File "/snap/sentry/70/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/snap/sentry/70/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/sentry/70/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/sentry/70/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/sentry/70/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/sentry/70/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/sentry/70/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/sentry/70/lib/python2.7/site-packages/sentry/runner/decorators.py", line 73, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/snap/sentry/70/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/sentry/70/lib/python2.7/site-packages/sentry/runner/commands/cleanup.py", line 151, in cleanup
    task_queue = Queue(1000)
  File "/snap/sentry/70/usr/lib/python2.7/multiprocessing/__init__.py", line 225, in JoinableQueue
    return JoinableQueue(maxsize)
  File "/snap/sentry/70/usr/lib/python2.7/multiprocessing/queues.py", line 300, in __init__
    Queue.__init__(self, maxsize)
  File "/snap/sentry/70/usr/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/snap/sentry/70/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/snap/sentry/70/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```
and kern.log says :
```
Mar 20 10:52:12 sentry kernel: [26218098.196288] audit: type=1400 audit(1584701532.328:95532): apparmor="DENIED" operation="open" profile="snap.sentry.sentry" name="/proc/20760/mounts" pid=20760 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 20 10:52:12 sentry kernel: [26218098.293746] audit: type=1400 audit(1584701532.428:95533): apparmor="DENIED" operation="mknod" profile="snap.sentry.sentry" name="/dev/shm/x7BWiS" pid=20760 comm="python2" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
```

**Comment by axinojolais** [comment]
As a workaround, I added :
```
/dev/shm/* mrwlkix,
```
to `/var/lib/snapd/apparmor/profiles/snap.sentry.sentry` and ran `sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.sentry.sentry` and this allowed `sentry cleanup` to work

**Comment by merlijn-sebrechts** [comment]
This should be fixed in the latest version. Please let us know and reopen this issue if it's not the case!
