### ISSUE TITLE
[Bug]: Worker service doesn't start due to Permission denied

### ISSUE THREAD

**Issue by red-abacus** [snapcrafters/sentry#42]
### What happened?

I am trying to run the latest version of sentry on Ubuntu 20.04. I followed all the steps from the Readme and  everything went well but the worker doesn't start and is continuously throwing a celery error that says that doesn't have permission to execute something from synchronize.py line 72.

### What should have happened?

When I finished with the steps from the Readme the worker should have ran properly.

### Output of `snap info $snap_name`

```shell
name:      sentry
summary:   Sentry is a modern error logging and aggregation platform
publisher: Snapcrafters
store-url: https://snapcraft.io/sentry
contact:   https://github.com/snapcrafters/sentry/issues
license:   unset
description: |
  Sentry’s real-time error tracking gives you insight
  into production deployments and information to reproduce
  and fix crashes.
commands:
  - sentry
services:
  sentry.cron:   simple, enabled, active
  sentry.web:    simple, enabled, active
  sentry.worker: simple, enabled, active
snap-id:      uHF1Xnb5hOMG7XFOR7vv5GCmLKSzBwE4
tracking:     latest/stable
refresh-date: today at 15:47 UTC
channels:
  latest/stable:    21.2.0 2022-05-12 (81) 145MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      21.2.0 2021-12-19 (81) 145MB -
installed:          21.2.0            (81) 145MB -s
```

### Output of `snap connections $snap_name`

```shell
Interface     Plug                 Slot           Notes
home          sentry:home          :home          -
network       sentry:network       :network       -
network-bind  sentry:network-bind  :network-bind  -
```

### Output of `snap version`

```shell
snap    2.56
snapd   2.56
series  16
ubuntu  20.04
kernel  5.13.0-1031-azure
```

### Relevant log output

```shell
Jun 23 16:09:14 sentry kernel: [ 1950.181536] audit: type=1400 audit(1656000554.556:682): apparmor="DENIED" operation="mknod" profile="snap.sentry.worker" name="/dev/shm/oSvbs3" pid=24344 comm=5B63656C657279643A2063656C6572 requested_mask="c" denied_mask="c" fsuid=0 ouid=0
Jun 23 16:09:15 sentry kernel: [ 1951.425722] audit: type=1400 audit(1656000555.800:683): apparmor="DENIED" operation="open" profile="snap.sentry.worker" name="/proc/24380/mounts" pid=24380 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jun 23 16:09:16 sentry kernel: [ 1952.124722] audit: type=1400 audit(1656000556.500:684): apparmor="DENIED" operation="open" profile="snap.sentry.worker" name="/proc/24380/mounts" pid=24380 comm="/snap/sentry/81" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

### Teminal output of app

```shell
Jun 23 15:58:50 sentry systemd[1]: Started Service for snap application sentry.worker.
Jun 23 15:58:52 sentry sentry.worker[21271]: 15:58:52 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
Jun 23 15:58:55 sentry sentry.worker[21271]: 15:58:55 [INFO] sentry.plugins.github: apps-not-configured
Jun 23 15:58:55 sentry sentry.worker[21271]: 15:58:55 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
Jun 23 15:58:55 sentry sentry.worker[21271]: 15:58:55 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')
Jun 23 15:58:56 sentry sentry.worker[21271]:  
Jun 23 15:58:56 sentry sentry.worker[21271]:  -------------- celery@sentry v4.4.7 (cliffs)
Jun 23 15:58:56 sentry sentry.worker[21271]: --- ***** -----
Jun 23 15:58:56 sentry sentry.worker[21271]: -- ******* ---- Linux-5.13.0-1031-azure-x86_64-with-Ubuntu-20.04-focal 2022-06-23 15:58:56
Jun 23 15:58:56 sentry sentry.worker[21271]: - *** --- * ---
Jun 23 15:58:56 sentry sentry.worker[21271]: - ** ---------- [config]
Jun 23 15:58:56 sentry sentry.worker[21271]: - ** ---------- .> app:         sentry:0x7f099c111400
Jun 23 15:58:56 sentry sentry.worker[21271]: - ** ---------- .> transport:   redis://localhost:6379//
Jun 23 15:58:56 sentry sentry.worker[21271]: - ** ---------- .> results:     disabled://
Jun 23 15:58:56 sentry sentry.worker[21271]: - *** --- * --- .> concurrency: 2 (prefork)
Jun 23 15:58:56 sentry sentry.worker[21271]: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
Jun 23 15:58:56 sentry sentry.worker[21271]: --- ***** -----
Jun 23 15:58:56 sentry sentry.worker[21271]:  -------------- [queues]
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> activity.notify  exchange=default(direct) key=activity.notify
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> alerts           exchange=default(direct) key=alerts
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> app_platform     exchange=default(direct) key=app_platform
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> assemble         exchange=default(direct) key=assemble
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> auth             exchange=default(direct) key=auth
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> buffers.process_pending exchange=default(direct) key=buffers.process_pending
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> cleanup          exchange=default(direct) key=cleanup
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> commits          exchange=default(direct) key=commits
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> counters-0       exchange=counters(direct) key=default
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> data_export      exchange=default(direct) key=data_export
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> default          exchange=default(direct) key=default
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> digests.delivery exchange=default(direct) key=digests.delivery
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> digests.scheduling exchange=default(direct) key=digests.scheduling
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> email            exchange=default(direct) key=email
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.preprocess_event exchange=default(direct) key=events.preprocess_event
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.process_event exchange=default(direct) key=events.process_event
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.reprocess_events exchange=default(direct) key=events.reprocess_events
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.reprocessing.preprocess_event exchange=default(direct) key=events.reprocessing.preprocess_event
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.reprocessing.process_event exchange=default(direct) key=events.reprocessing.process_event
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.reprocessing.symbolicate_event exchange=default(direct) key=events.reprocessing.symbolicate_event
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.save_event exchange=default(direct) key=events.save_event
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> events.symbolicate_event exchange=default(direct) key=events.symbolicate_event
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> files.delete     exchange=default(direct) key=files.delete
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> group_owners.process_suspect_commits exchange=default(direct) key=group_owners.process_suspect_commits
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> incident_snapshots exchange=default(direct) key=incident_snapshots
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> incidents        exchange=default(direct) key=incidents
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> integrations     exchange=default(direct) key=integrations
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> merge            exchange=default(direct) key=merge
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> options          exchange=default(direct) key=options
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> relay_config     exchange=default(direct) key=relay_config
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> reports.deliver  exchange=default(direct) key=reports.deliver
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> reports.prepare  exchange=default(direct) key=reports.prepare
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> search           exchange=default(direct) key=search
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> sleep            exchange=default(direct) key=sleep
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> stats            exchange=default(direct) key=stats
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> subscriptions    exchange=default(direct) key=subscriptions
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> triggers-0       exchange=triggers(direct) key=default
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> unmerge          exchange=default(direct) key=unmerge
Jun 23 15:58:56 sentry sentry.worker[21271]:                 .> update           exchange=default(direct) key=update
Jun 23 15:58:56 sentry sentry.worker[21271]: Traceback (most recent call last):
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/celery/worker/worker.py", line 208, in start
Jun 23 15:58:56 sentry sentry.worker[21271]:     self.blueprint.start(self)
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
Jun 23 15:58:56 sentry sentry.worker[21271]:     step.start(parent)
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
Jun 23 15:58:56 sentry sentry.worker[21271]:     return self.obj.start()
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/celery/concurrency/base.py", line 132, in start
Jun 23 15:58:56 sentry sentry.worker[21271]:     self.on_start()
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 117, in on_start
Jun 23 15:58:56 sentry sentry.worker[21271]:     **self.options)
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 486, in __init__
Jun 23 15:58:56 sentry sentry.worker[21271]:     super(AsynPool, self).__init__(processes, *args, **kwargs)
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/billiard/pool.py", line 1046, in __init__
Jun 23 15:58:56 sentry sentry.worker[21271]:     self._create_worker_process(i)
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 503, in _create_worker_process
Jun 23 15:58:56 sentry sentry.worker[21271]:     return super(AsynPool, self)._create_worker_process(i)
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/billiard/pool.py", line 1142, in _create_worker_process
Jun 23 15:58:56 sentry sentry.worker[21271]:     on_ready_counter = self._ctx.Value('i')
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/billiard/context.py", line 182, in Value
Jun 23 15:58:56 sentry sentry.worker[21271]:     ctx=self.get_context())
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/billiard/sharedctypes.py", line 83, in Value
Jun 23 15:58:56 sentry sentry.worker[21271]:     lock = ctx.RLock()
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/billiard/context.py", line 110, in RLock
Jun 23 15:58:56 sentry sentry.worker[21271]:     return RLock(ctx=self.get_context())
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/billiard/synchronize.py", line 207, in __init__
Jun 23 15:58:56 sentry sentry.worker[21271]:     SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
Jun 23 15:58:56 sentry sentry.worker[21271]:   File "/snap/sentry/81/lib/python3.6/site-packages/billiard/synchronize.py", line 72, in __init__
Jun 23 15:58:56 sentry sentry.worker[21271]:     kind, value, maxvalue, self._make_name(), unlink_now,
Jun 23 15:58:56 sentry sentry.worker[21271]: PermissionError: [Errno 13] Permission denied
Jun 23 15:58:56 sentry sentry.worker[21271]: 15:58:56 [CRITICAL] celery.worker: Unrecoverable error: PermissionError(13, 'Permission denied')
Jun 23 15:58:56 sentry sentry.worker[21271]: 15:58:56 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
Jun 23 15:58:56 sentry sentry.worker[21271]: 15:58:56 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')
Jun 23 15:58:56 sentry sentry.worker[21271]: /snap/sentry/81/lib/python3.6/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
Jun 23 15:58:56 sentry sentry.worker[21271]: absolutely not recommended!
Jun 23 15:58:56 sentry sentry.worker[21271]: Please specify a different user using the --uid option.
Jun 23 15:58:56 sentry sentry.worker[21271]: User information: uid=0 euid=0 gid=0 egid=0
Jun 23 15:58:56 sentry sentry.worker[21271]:   uid=uid, euid=euid, gid=gid, egid=egid,
```

**Comment by michaeldojcar** [comment]
I have same problem with fresh installation.

**Comment by vmpjdc** [comment]
I believe this is due to a bug/limitation in snapd with strictly-confined snaps and celery's use of SemLock. I've filed a bug report here: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1986594
